export const String = {
  digital_access: 'Digit Access Code',
  digital_access_code: 'Digit access code sent to +96 8364 9838 93',
  notification: 'Notification',
  See_All: 'See All',
  recent_searches: 'Recent Searches',
  list: 'LIST',
  map: 'MAP',
  location_text: 'Click me to get location',
  select_location: 'Select location',
  landmark: 'search for area, landmark...',
  current_location: 'Current location',
  using_gps: 'Using GPS',
  nearBy: 'Nearby locations',
  recentText: 'Recent locations',
  sale: 'SALE',
  purchase: 'PURCHASED',
  request: 'REQUEST',
  view: 'VIEW',
};
