import {ImagePath} from '../../../ImageConstant';

export const Array = [
  {
    Title: 'Dinner in The Sky',
    subText: '4814 Bingamon Road Warrensville Heights, OH 44128',
    ImageName: ImagePath.WaitsScreen1,
    star: '5.0',
    starCount: 214,
    price: '$50.00',
    waitCapacity: 8,
    date: '10 July 2021',
    token: false,
    waitType: 'Window',
    time: '08:00PM',
  },
  {
    Title: 'Dinner in The Bath',
    subText: 'chimanpura peth, satara',
    ImageName: ImagePath.Girl,
    star: '5.0',
    starCount: 214,
    price: '$50.00',
    waitCapacity: 8,
    date: '10 July 2021',
    token: false,
    waitType: 'Window',
    time: '08:00PM',
  },
  {
    Title: 'The Fun Station',
    subText: '4814 Bingamon Road Warrensville Heights, OH 44128',
    ImageName: ImagePath.Golf,
    star: '5.0',
    starCount: 214,
    price: '$50.00',
    waitCapacity: 8,
    date: '10 July 2021',
    token: false,
    waitType: 'Window',
    time: '08:00PM',
  },
  {
    Title: 'The Disaster Cafe',
    subText: '4814 Bingamon Road Warrensville Heights, OH 44128',
    ImageName: ImagePath.Chair,
    star: '5.0',
    starCount: 214,
    price: '$50.00',
    waitCapacity: 8,
    date: '10 July 2021',
    token: false,
    waitType: 'Window',
    time: '08:00PM',
  },
  {
    Title: 'Del Posto',
    subText: '4814 Bingamon Road Warrensville Heights, OH 44128',
    ImageName: ImagePath.Lest,
    star: '5.0',
    starCount: 214,
    price: '$50.00',
    waitCapacity: 8,
    date: '10 July 2021',
    token: false,
    waitType: 'Window',
    time: '08:00PM',
  },
  {
    Title: 'Comedy knockout',
    subText: '4814 Bingamon Road Warrensville Heights, OH 44128',
    ImageName: ImagePath.Song,
    star: '5.0',
    starCount: 214,
    price: '$50.00',
    waitCapacity: 8,
    date: '10 July 2021',
    token: false,
    waitType: 'Window',
    time: '08:00PM',
  },
  {
    Title: 'Parallax Restaurant',
    subText: '4814 Bingamon Road Warrensville Heights, OH 44128',
    ImageName: ImagePath.Veg,
    star: '5.0',
    starCount: 214,
    price: '$50.00',
    waitCapacity: 8,
    date: '10 July 2021',
    token: false,
    waitType: 'Window',
    time: '08:00PM',
  },
  {
    Title: 'Parallax Restaurant',
    subText: '4814 Bingamon Road Warrensville Heights, OH 44128',
    ImageName: ImagePath.Cafe,
    star: '5.0',
    starCount: 214,
    price: '$50.00',
    waitCapacity: 8,
    date: '10 July 2021',
    token: false,
    waitType: 'Window',
    time: '08:00PM',
  },
  {
    Title: 'Spa and Wellness',
    subText: '4814 Bingamon Road Warrensville Heights, OH 44128',
    ImageName: ImagePath.Spa,
    star: '5.0',
    starCount: 214,
    price: '$50.00',
    waitCapacity: 8,
    date: '10 July 2021',
    token: false,
    waitType: 'Window',
    time: '08:00PM',
  },
  {
    Title: 'Sequia Hotel',
    subText: '4814 Bingamon Road Warrensville Heights, OH 44128',
    ImageName: ImagePath.Lodge,
    star: '5.0',
    starCount: 214,
    price: '$50.00',
    waitCapacity: 8,
    date: '10 July 2021',
    token: false,
    waitType: 'Window',
    time: '08:00PM',
  },
  {
    Title: 'Paris in The Sky',
    subText: '4814 Bingamon Road Warrensville Heights, OH 44128',
    ImageName: ImagePath.Paris,
    star: '5.0',
    starCount: 214,
    price: '$50.00',
    waitCapacity: 8,
    date: '10 July 2021',
    token: false,
    waitType: 'Window',
    time: '08:00PM',
  },
];
